// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgYjX18j7XK9KhT-gtmIVlqZr59iWuhP8',
    appId: '1:971335277078:web:5b3aa37f0d3c3fa11a7337',
    messagingSenderId: '971335277078',
    projectId: 'skincore-64069',
    authDomain: 'skincore-64069.firebaseapp.com',
    storageBucket: 'skincore-64069.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKLVs-CENUSd7FyZJrVzeZcPtCWHk993o',
    appId: '1:971335277078:android:55808f42334c265a1a7337',
    messagingSenderId: '971335277078',
    projectId: 'skincore-64069',
    storageBucket: 'skincore-64069.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByG84jk_UErJT4JE2VaIF0Q2UwInFtMyA',
    appId: '1:971335277078:ios:7768b04ce696d2d51a7337',
    messagingSenderId: '971335277078',
    projectId: 'skincore-64069',
    storageBucket: 'skincore-64069.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByG84jk_UErJT4JE2VaIF0Q2UwInFtMyA',
    appId: '1:971335277078:ios:7768b04ce696d2d51a7337',
    messagingSenderId: '971335277078',
    projectId: 'skincore-64069',
    storageBucket: 'skincore-64069.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgYjX18j7XK9KhT-gtmIVlqZr59iWuhP8',
    appId: '1:971335277078:web:0b484276142515311a7337',
    messagingSenderId: '971335277078',
    projectId: 'skincore-64069',
    authDomain: 'skincore-64069.firebaseapp.com',
    storageBucket: 'skincore-64069.firebasestorage.app',
  );
}
