import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('hi'),
    Locale('mr'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // App & Common
      'app_name': 'SkinCore AI',
      'common_ok': 'OK',
      'common_cancel': 'Cancel',
      'common_confirm': 'Confirm',
      'common_close': 'Close',
      'common_save': 'Save',
      'common_delete': 'Delete',
      'common_retry': 'Retry',
      'common_back': 'Back',
      'common_next': 'Next',
      'common_done': 'Done',
      'common_error': 'Error',
      'common_success': 'Success',
      'common_warning': 'Warning',
      'common_loading': 'Loading...',
      'common_no_data': 'No data available',
      'language_select': 'Language',
      'language_english': 'English',
      'language_hindi': 'हिन्दी',
      'language_marathi': 'मराठी',

      // Navigation
      'nav_home': 'Home',
      'nav_scan': 'Skin Scan',
      'nav_questionnaire': 'Questionnaire',
      'nav_recommendations': 'Products',
      'nav_tracker': 'Progress',
      'nav_chatbot': 'AI Assistant',
      'nav_settings': 'Settings',
      'nav_profile': 'Profile',

      // Authentication
      'auth_welcome_back': 'Welcome back',
      'auth_create_account': 'Create Account',
      'auth_login_subtitle': 'Sign in to continue your skin journey',
      'auth_signup_subtitle': 'Register as a new member to start your skin journey',
      'auth_email_hint': 'Email address',
      'auth_password_hint': 'Password',
      'auth_confirm_password_hint': 'Confirm Password',
      'auth_forgot_password': 'Forgot password?',
      'auth_login_button': 'Log in',
      'auth_signup_button': 'Create Account',
      'auth_or_continue_with': 'or continue with',
      'auth_google_continue': 'Continue with Google',
      'auth_dont_have_account': "Don't have an account? ",
      'auth_already_have_account': 'Already have an account? ',
      'auth_sign_up_link': 'Sign up',
      'auth_log_in_link': 'Log in',
      'auth_show_password': 'Show password',
      'auth_hide_password': 'Hide password',
      'auth_invalid_email': 'Please enter a valid email address.',
      'auth_short_password': 'Password must be at least 6 characters.',
      'auth_password_mismatch': 'Passwords do not match.',
      'auth_account_exists': 'An account with this email already exists. Please log in.',
      'auth_email_registered_firebase': 'This email is already registered in Firebase. Please log in.',
      'auth_account_created_title': 'Account Created Successfully!',
      'auth_account_created_sub': 'You can now log into your account.',
      'auth_log_in_now': 'Log In Now',
      'auth_incorrect_password': 'Incorrect password. Please try again.',
      'auth_account_not_found': 'Account not found. Click "Sign up" below to create a new member account.',
      'auth_failed': 'Authentication failed',
      'auth_google_failed': 'Google sign-in failed.',
      'auth_sign_out': 'Sign out',

      // Home Screen
      'home_greeting_morning': 'Good Morning,',
      'home_greeting_afternoon': 'Good Afternoon,',
      'home_greeting_evening': 'Good Evening,',
      'home_welcome_hero': 'Personalized AI Skin Intelligence',
      'home_start_scan_title': 'Analyze Your Skin',
      'home_start_scan_sub': 'Take or upload a photo for Instant AI Analysis & GradCAM Mapping',
      'home_start_scan_button': 'Start Skin Scan',
      'home_routine_title': 'Today\'s Skincare Routine',
      'home_morning_routine': 'Morning Routine',
      'home_evening_routine': 'Evening Routine',
      'home_custom_routine': 'Custom Routine',
      'home_no_routines': 'No skincare routines scheduled for today.',
      'home_add_routine': 'Add Routine',
      'home_skin_score': 'Skin Health Score',
      'home_recent_analysis': 'Recent Scan Reports',
      'home_view_all': 'View All',
      'home_view_details': 'View Details',
      'home_myths_title': 'Skincare Myths & Facts',
      'home_take_quiz': 'Take Quiz',
      'home_quick_questionnaire': 'Complete Skin Questionnaire',
      'home_quick_questionnaire_sub': 'Get tailored product & routine recommendations',

      // Skin Scan Screen
      'scan_title': 'Skin Scan & AI Analysis',
      'scan_subtitle': 'MobileNetV2 Local Inference + Ephemeral Groq Vision',
      'scan_take_photo': 'Take Photo',
      'scan_gallery': 'Choose from Gallery',
      'scan_upload_prompt': 'Capture or upload a clear photo of your skin area',
      'scan_analyzing': 'Analyzing Skin...',
      'scan_processing_sub': 'Running MobileNetV2 neural feature extraction',
      'scan_condition_detected': 'Detected Condition',
      'scan_confidence': 'Confidence',
      'scan_secondary_possibilities': 'Secondary Possibilities',
      'scan_region_analysis': 'Facial Zone Analysis',
      'scan_gradcam_overlay': 'GradCAM Visual Heatmap',
      'scan_recommended_actions': 'Recommended Care Actions',
      'scan_disclaimer': 'Medical Disclaimer: SkinCore AI is for informational guidance and non-diagnostic triage. Consult a licensed dermatologist for clinical medical advice.',
      'scan_retake': 'Retake Photo',
      'scan_save_report': 'Save Medical Report',
      'scan_report_saved': 'Report saved successfully!',

      // Questionnaire Screen
      'q_title': 'Skin Profile Questionnaire',
      'q_subtitle': 'Tell us about your skin to personalize your recommendations',
      'q_step': 'Step',
      'q_of': 'of',
      'q_skin_type': 'What is your primary skin type?',
      'q_primary_concern': 'What is your main skin concern?',
      'q_sensitivity': 'How sensitive is your skin?',
      'q_sun_exposure': 'How often are you exposed to direct sunlight?',
      'q_budget': 'What is your preferred product budget range?',
      'q_submit': 'Submit Questionnaire',
      'q_submitting': 'Saving Profile...',
      'q_success': 'Questionnaire completed successfully!',
      'q_retake': 'Update Questionnaire Answers',

      // Skin types & options
      'opt_oily': 'Oily',
      'opt_dry': 'Dry',
      'opt_combination': 'Combination',
      'opt_normal': 'Normal',
      'opt_sensitive': 'Sensitive',
      'opt_acne': 'Acne & Breakouts',
      'opt_aging': 'Fine Lines & Aging',
      'opt_pigmentation': 'Pigmentation & Dark Spots',
      'opt_redness': 'Redness & Rosacea',
      'opt_low': 'Low / Gentle',
      'opt_medium': 'Moderate',
      'opt_high': 'High / Sensitive',
      'opt_budget_low': 'Budget Friendly (₹ / \$)',
      'opt_budget_mid': 'Mid-range (₹₹ / \$\$)',
      'opt_budget_premium': 'Premium (₹₹₹ / \$\$\$)',

      // Products & Recommendations
      'reco_title': 'Ingredient-First Recommendations',
      'reco_subtitle': 'Brand-neutral products matching your skin analysis & profile',
      'reco_prereq_title': 'Complete Your Profile First',
      'reco_prereq_sub': 'Take a skin scan or fill out the questionnaire to unlock personalized product recommendations.',
      'reco_prereq_scan_btn': 'Take Skin Scan',
      'reco_prereq_q_btn': 'Complete Questionnaire',
      'reco_tab_all': 'All Products',
      'reco_tab_cleanser': 'Cleansers',
      'reco_tab_moisturizer': 'Moisturizers',
      'reco_tab_sunscreen': 'Sunscreens',
      'reco_tab_serum': 'Serums',
      'reco_tab_treatment': 'Treatments',
      'reco_suitable_high': 'Highly Suitable',
      'reco_suitable_med': 'Moderately Suitable',
      'reco_suitable_low': 'Use with Caution',
      'reco_why_recommended': 'Why Recommended',
      'reco_key_actives': 'Key Active Ingredients',
      'reco_ingredients_avoid': 'Ingredients to Avoid',
      'reco_usage_tips': 'How to Use',
      'reco_buy_now': 'View / Buy Product',
      'reco_brand_neutral': 'Brand Neutral & Transparent',
      'reco_no_products': 'No products found for this category.',

      // Progress Tracker
      'tracker_title': 'Progress & History',
      'tracker_subtitle': 'Track your skincare routine adherence and scan history',
      'tracker_routine_adherence': 'Routine Adherence',
      'tracker_morning_done': 'Morning Routine Completed',
      'tracker_evening_done': 'Evening Routine Completed',
      'tracker_streak': 'Day Streak',
      'tracker_scan_history': 'Scan History Reports',
      'tracker_no_history': 'No scan reports recorded yet.',
      'tracker_add_routine_btn': '+ Add Routine Item',
      'tracker_routine_item_name': 'Routine Item Name',
      'tracker_routine_time': 'Time',

      // Chatbot
      'chat_title': 'SkinCore AI Assistant',
      'chat_subtitle': 'Ask any skincare, ingredient, or routine question',
      'chat_placeholder': 'Ask SkinCore AI about your skin...',
      'chat_disclaimer': 'AI advice is for general skincare awareness. Consult a physician for medical diagnosis.',
      'chat_prompt_1': 'What routine is best for oily skin?',
      'chat_prompt_2': 'How do I use Salicylic Acid safely?',
      'chat_prompt_3': 'Explain sunscreen SPF ratings.',

      // Settings
      'settings_title': 'Settings & Profile',
      'settings_dark_mode': 'Dark Mode',
      'settings_smart_notifs': 'Smart Notifications',
      'settings_smart_notifs_sub': 'Automated skincare routine reminders',
      'settings_language': 'Language',
      'settings_privacy': 'Privacy & Data',
      'settings_privacy_sub': 'Manage telemetry, local logs & scan cache',
      'settings_clear_cache': 'Clear Scan Cache',
      'settings_export_data': 'Export Medical Data',
      'settings_delete_data': 'Delete Medical Data',
      'settings_delete_confirm_title': 'Delete Medical History?',
      'settings_delete_confirm_body': 'This action cannot be undone. All saved skin scan reports and local history will be erased.',

      // Medical condition display labels (UI presentation only)
      'cond_acne_vulgaris': 'Acne Vulgaris',
      'cond_eczema': 'Eczema / Dermatitis',
      'cond_melasma': 'Melasma / Hyperpigmentation',
      'cond_rosacea': 'Rosacea / Facial Redness',
      'cond_psoriasis': 'Psoriasis',
      'cond_normal_healthy': 'Healthy Skin',
      'cond_unknown': 'Skin Condition Analysis',
    },
    'hi': {
      // App & Common
      'app_name': 'स्किनकोर AI',
      'common_ok': 'ठीक है',
      'common_cancel': 'रद्द करें',
      'common_confirm': 'पुष्टि करें',
      'common_close': 'बंद करें',
      'common_save': 'सहेजे',
      'common_delete': 'हटाएं',
      'common_retry': 'पुनः प्रयास करें',
      'common_back': 'वापस',
      'common_next': 'आगे',
      'common_done': 'संपन्न',
      'common_error': 'त्रुटि',
      'common_success': 'सफलता',
      'common_warning': 'चेतावनी',
      'common_loading': 'लोड हो रहा है...',
      'common_no_data': 'कोई डेटा उपलब्ध नहीं है',
      'language_select': 'भाषा',
      'language_english': 'English',
      'language_hindi': 'हिन्दी',
      'language_marathi': 'मराठी',

      // Navigation
      'nav_home': 'मुख्य पृष्ठ',
      'nav_scan': 'त्वचा स्कैन',
      'nav_questionnaire': 'प्रश्नावली',
      'nav_recommendations': 'उत्पाद',
      'nav_tracker': 'प्रगति',
      'nav_chatbot': 'AI सहायक',
      'nav_settings': 'सेटिंग्स',
      'nav_profile': 'प्रोफ़ाइल',

      // Authentication
      'auth_welcome_back': 'पुनः स्वागत है',
      'auth_create_account': 'खाता बनाएं',
      'auth_login_subtitle': 'अपनी त्वचा देखभाल यात्रा जारी रखने के लिए साइन इन करें',
      'auth_signup_subtitle': 'अपनी त्वचा यात्रा शुरू करने के लिए नए सदस्य के रूप में पंजीकरण करें',
      'auth_email_hint': 'ईमेल पता',
      'auth_password_hint': 'पासवर्ड',
      'auth_confirm_password_hint': 'पासवर्ड की पुष्टि करें',
      'auth_forgot_password': 'पासवर्ड भूल गए?',
      'auth_login_button': 'लॉग इन करें',
      'auth_signup_button': 'खाता बनाएं',
      'auth_or_continue_with': 'या इसके साथ आगे बढ़ें',
      'auth_google_continue': 'Google के साथ आगे बढ़ें',
      'auth_dont_have_account': 'क्या आपके पास खाता नहीं है? ',
      'auth_already_have_account': 'क्या आपके पास पहले से खाता है? ',
      'auth_sign_up_link': 'साइन अप करें',
      'auth_log_in_link': 'लॉग इन करें',
      'auth_show_password': 'पासवर्ड दिखाएं',
      'auth_hide_password': 'पासवर्ड छिपाएं',
      'auth_invalid_email': 'कृपया एक मान्य ईमेल पता दर्ज करें।',
      'auth_short_password': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
      'auth_password_mismatch': 'पासवर्ड मेल नहीं खाते।',
      'auth_account_exists': 'इस ईमेल के साथ एक खाता पहले से मौजूद है। कृपया लॉग इन करें।',
      'auth_email_registered_firebase': 'यह ईमेल पहले से पंजीकृत है। कृपया लॉग इन करें।',
      'auth_account_created_title': 'खाता सफलतापूर्वक बनाया गया!',
      'auth_account_created_sub': 'अब आप अपने खाते में लॉग इन कर सकते हैं।',
      'auth_log_in_now': 'अब लॉग इन करें',
      'auth_incorrect_password': 'गलत पासवर्ड। कृपया पुनः प्रयास करें।',
      'auth_account_not_found': 'खाता नहीं मिला। नया खाता बनाने के लिए नीचे "साइन अप करें" पर क्लिक करें।',
      'auth_failed': 'प्रमाणीकरण विफल रहा',
      'auth_google_failed': 'गूगल साइन-इन विफल रहा।',
      'auth_sign_out': 'साइन आउट करें',

      // Home Screen
      'home_greeting_morning': 'शुभ प्रभात,',
      'home_greeting_afternoon': 'शुभ दोपहर,',
      'home_greeting_evening': 'शुभ संध्या,',
      'home_welcome_hero': 'व्यक्तिगत AI त्वचा बुद्धिमत्ता',
      'home_start_scan_title': 'अपनी त्वचा का विश्लेषण करें',
      'home_start_scan_sub': 'त्वरित AI विश्लेषण और GradCAM मैपिंग के लिए फोटो लें या अपलोड करें',
      'home_start_scan_button': 'त्वचा स्कैन शुरू करें',
      'home_routine_title': 'आज की त्वचा देखभाल दिनचर्या',
      'home_morning_routine': 'सुबह की दिनचर्या',
      'home_evening_routine': 'शाम की दिनचर्या',
      'home_custom_routine': 'कस्टम दिनचर्या',
      'home_no_routines': 'आज के लिए कोई त्वचा देखभाल दिनचर्या निर्धारित नहीं है।',
      'home_add_routine': 'दिनचर्या जोड़ें',
      'home_skin_score': 'त्वचा स्वास्थ्य स्कोर',
      'home_recent_analysis': 'हालिया स्कैन रिपोर्ट',
      'home_view_all': 'सभी देखें',
      'home_view_details': 'विवरण देखें',
      'home_myths_title': 'त्वचा देखभाल के भ्रम और तथ्य',
      'home_take_quiz': 'क्विज लें',
      'home_quick_questionnaire': 'त्वचा प्रश्नावली पूरी करें',
      'home_quick_questionnaire_sub': 'अनुकूलित उत्पाद और दिनचर्या सिफारिशें प्राप्त करें',

      // Skin Scan Screen
      'scan_title': 'त्वचा स्कैन और AI विश्लेषण',
      'scan_subtitle': 'स्थानीय मोबाइलनेटV2 अनुमान और सुरक्षित AI विश्लेषण',
      'scan_take_photo': 'फोटो लें',
      'scan_gallery': 'गैलरी से चुनें',
      'scan_upload_prompt': 'अपनी त्वचा के क्षेत्र की एक स्पष्ट फोटो लें या अपलोड करें',
      'scan_analyzing': 'त्वचा का विश्लेषण हो रहा है...',
      'scan_processing_sub': 'मोबाइलनेटV2 न्यूरल फीचर निष्कर्षण चल रहा है',
      'scan_condition_detected': 'पहचानी गई स्थिति',
      'scan_confidence': 'सटीकता दर',
      'scan_secondary_possibilities': 'अन्य संभावनाएं',
      'scan_region_analysis': 'चेहरे के क्षेत्र का विश्लेषण',
      'scan_gradcam_overlay': 'GradCAM विजुअल हीटमैप',
      'scan_recommended_actions': 'अनुशंसित देखभाल कार्य',
      'scan_disclaimer': 'चिकित्सा अस्वीकरण: स्किनकोर AI केवल सूचनात्मक मार्गदर्शन के लिए है। नैदानिक चिकित्सा सलाह के लिए त्वचा विशेषज्ञ से परामर्श लें।',
      'scan_retake': 'दोबारा फोटो लें',
      'scan_save_report': 'रिपोर्ट सहेजें',
      'scan_report_saved': 'रिपोर्ट सफलतापूर्वक सहेजी गई!',

      // Questionnaire Screen
      'q_title': 'त्वचा प्रोफ़ाइल प्रश्नावली',
      'q_subtitle': 'अपनी सिफारिशों को व्यक्तिगत बनाने के लिए अपनी त्वचा के बारे में बताएं',
      'q_step': 'चरण',
      'q_of': 'का',
      'q_skin_type': 'आपकी प्राथमिक त्वचा का प्रकार क्या है?',
      'q_primary_concern': 'आपकी मुख्य त्वचा की समस्या क्या है?',
      'q_sensitivity': 'आपकी त्वचा कितनी संवेदनशील है?',
      'q_sun_exposure': 'आप सीधे धूप में कितनी बार संपर्क में आते हैं?',
      'q_budget': 'आपकी पसंदीदा उत्पाद बजट श्रेणी क्या है?',
      'q_submit': 'प्रश्नावली जमा करें',
      'q_submitting': 'प्रोफ़ाइल सहेजी जा रही है...',
      'q_success': 'प्रश्नावली सफलतापूर्वक पूरी हुई!',
      'q_retake': 'प्रश्नावली उत्तर अपडेट करें',

      // Skin types & options
      'opt_oily': 'तैलीय (Oily)',
      'opt_dry': 'शुष्क (Dry)',
      'opt_combination': 'मिश्रित (Combination)',
      'opt_normal': 'सामान्य (Normal)',
      'opt_sensitive': 'संवेदनशील (Sensitive)',
      'opt_acne': 'मुहासे और दाने (Acne)',
      'opt_aging': 'महीन रेखाएं और झुर्रियां',
      'opt_pigmentation': 'पिगमेंटेशन और काले धब्बे',
      'opt_redness': 'लालिमा (Redness)',
      'opt_low': 'कम / हल्का',
      'opt_medium': 'मध्यम',
      'opt_high': 'उच्च / संवेदनशील',
      'opt_budget_low': 'किफायती (₹ / \$)',
      'opt_budget_mid': 'मध्यम वर्ग (₹₹ / \$\$)',
      'opt_budget_premium': 'प्रीमियम (₹₹₹ / \$\$\$)',

      // Products & Recommendations
      'reco_title': 'सामग्री-प्रथम सिफारिशें',
      'reco_subtitle': 'आपकी त्वचा विश्लेषण और प्रोफ़ाइल से मेल खाने वाले उत्पाद',
      'reco_prereq_title': 'पहले अपनी प्रोफ़ाइल पूरी करें',
      'reco_prereq_sub': 'व्यक्तिगत उत्पाद सिफारिशों को अनलॉक करने के लिए त्वचा स्कैन लें या प्रश्नावली भरें।',
      'reco_prereq_scan_btn': 'त्वचा स्कैन लें',
      'reco_prereq_q_btn': 'प्रश्नावली पूरी करें',
      'reco_tab_all': 'सभी उत्पाद',
      'reco_tab_cleanser': 'क्लींजर',
      'reco_tab_moisturizer': 'मॉइस्चराइज़र',
      'reco_tab_sunscreen': 'सनस्क्रीन',
      'reco_tab_serum': 'सीरम',
      'reco_tab_treatment': 'उपचार (Treatment)',
      'reco_suitable_high': 'अत्यधिक उपयुक्त',
      'reco_suitable_med': 'मध्यम उपयुक्त',
      'reco_suitable_low': 'सावधानी से उपयोग करें',
      'reco_why_recommended': 'सिफारिश का कारण',
      'reco_key_actives': 'मुख्य सक्रिय तत्व',
      'reco_ingredients_avoid': 'परहेज योग्य तत्व',
      'reco_usage_tips': 'उपयोग कैसे करें',
      'reco_buy_now': 'उत्पाद देखें / खरीदें',
      'reco_brand_neutral': 'ब्रांड तटस्थ और पारदर्शी',
      'reco_no_products': 'इस श्रेणी के लिए कोई उत्पाद नहीं मिला।',

      // Progress Tracker
      'tracker_title': 'प्रगति और इतिहास',
      'tracker_subtitle': 'अपनी त्वचा देखभाल दिनचर्या और स्कैन इतिहास को ट्रैक करें',
      'tracker_routine_adherence': 'दिनचर्या पालन',
      'tracker_morning_done': 'सुबह की दिनचर्या पूरी हुई',
      'tracker_evening_done': 'शाम की दिनचर्या पूरी हुई',
      'tracker_streak': 'दिनों की निरंतरता',
      'tracker_scan_history': 'स्कैन इतिहास रिपोर्ट',
      'tracker_no_history': 'अभी तक कोई स्कैन रिपोर्ट दर्ज नहीं की गई है।',
      'tracker_add_routine_btn': '+ दिनचर्या आइटम जोड़ें',
      'tracker_routine_item_name': 'दिनचर्या आइटम नाम',
      'tracker_routine_time': 'समय',

      // Chatbot
      'chat_title': 'स्किनकोर AI सहायक',
      'chat_subtitle': 'त्वचा देखभाल, सामग्री या दिनचर्या का कोई भी प्रश्न पूछें',
      'chat_placeholder': 'स्किनकोर AI से अपनी त्वचा के बारे में पूछें...',
      'chat_disclaimer': 'AI सलाह सामान्य जागरूकता के लिए है। चिकित्सा निदान के लिए डॉक्टर से परामर्श करें।',
      'chat_prompt_1': 'तैलीय त्वचा के लिए सबसे अच्छी दिनचर्या क्या है?',
      'chat_prompt_2': 'सेलिसिलिक एसिड का सुरक्षित उपयोग कैसे करें?',
      'chat_prompt_3': 'सनस्क्रीन SPF रेटिंग समझाएं।',

      // Settings
      'settings_title': 'सेटिंग्स और प्रोफ़ाइल',
      'settings_dark_mode': 'डार्क मोड',
      'settings_smart_notifs': 'स्मार्ट सूचनाएं',
      'settings_smart_notifs_sub': 'स्वचालित त्वचा देखभाल दिनचर्या अनुस्मारक',
      'settings_language': 'भाषा',
      'settings_privacy': 'गोपनीयता और डेटा',
      'settings_privacy_sub': 'डेटा, स्थानीय लॉग और कैश प्रबंधित करें',
      'settings_clear_cache': 'स्कैन कैश साफ़ करें',
      'settings_export_data': 'डेटा निर्यात करें',
      'settings_delete_data': 'डेटा हटाएं',
      'settings_delete_confirm_title': 'इतिहास हटाएं?',
      'settings_delete_confirm_body': 'यह कार्रवाई पूर्ववत नहीं की जा सकती। सभी सहेजी गई स्कैन रिपोर्ट हटा दी जाएंगी।',

      // Medical condition display labels
      'cond_acne_vulgaris': 'एक्ने / मुहासे (Acne Vulgaris)',
      'cond_eczema': 'एक्जिमा / दाद (Eczema)',
      'cond_melasma': 'मेलास्मा / झाइयां (Melasma)',
      'cond_rosacea': 'रोसेशिया / लालिमा (Rosacea)',
      'cond_psoriasis': 'सोरायसिस (Psoriasis)',
      'cond_normal_healthy': 'स्वस्थ त्वचा',
      'cond_unknown': 'त्वचा स्थिति विश्लेषण',
    },
    'mr': {
      // App & Common
      'app_name': 'स्किनकोर AI',
      'common_ok': 'ठीक आहे',
      'common_cancel': 'रद्द करा',
      'common_confirm': 'खात्री करा',
      'common_close': 'बंद करा',
      'common_save': 'जतन करा',
      'common_delete': 'हटवा',
      'common_retry': 'पुन्हा प्रयत्न करा',
      'common_back': 'मागे',
      'common_next': 'पुढे',
      'common_done': 'पूर्ण',
      'common_error': 'त्रुटी',
      'common_success': 'यश',
      'common_warning': 'तकीद',
      'common_loading': 'लोड होत आहे...',
      'common_no_data': 'कोणताही डेटा उपलब्ध नाही',
      'language_select': 'भाषा',
      'language_english': 'English',
      'language_hindi': 'हिन्दी',
      'language_marathi': 'मराठी',

      // Navigation
      'nav_home': 'मुख्य पृष्ठ',
      'nav_scan': 'त्वचा स्कॅन',
      'nav_questionnaire': 'प्रश्नावली',
      'nav_recommendations': 'उत्पादने',
      'nav_tracker': 'प्रगती',
      'nav_chatbot': 'AI सहाय्यक',
      'nav_settings': 'सेटिंग्ज',
      'nav_profile': 'प्रोफाइल',

      // Authentication
      'auth_welcome_back': 'पुन्हा स्वागत आहे',
      'auth_create_account': 'खाते तयार करा',
      'auth_login_subtitle': 'तुमचा त्वचा काळजी प्रवास सुरू ठेवण्यासाठी साइन इन करा',
      'auth_signup_subtitle': 'नवीन सदस्य म्हणून नोंदणी करा आणि प्रवास सुरू करा',
      'auth_email_hint': 'ईमेल पत्ता',
      'auth_password_hint': 'पासवर्ड',
      'auth_confirm_password_hint': 'पासवर्डची खात्री करा',
      'auth_forgot_password': 'पासवर्ड विसरलात?',
      'auth_login_button': 'लॉग इन करा',
      'auth_signup_button': 'खाते तयार करा',
      'auth_or_continue_with': 'किंवा याद्वारे पुढे जा',
      'auth_google_continue': 'Google सह पुढे जा',
      'auth_dont_have_account': 'खाते नाही आहे? ',
      'auth_already_have_account': 'आधीपासून खाते आहे? ',
      'auth_sign_up_link': 'साइन अप करा',
      'auth_log_in_link': 'लॉग इन करा',
      'auth_show_password': 'पासवर्ड दाखवा',
      'auth_hide_password': 'पासवर्ड लपवा',
      'auth_invalid_email': 'कृपया वैध ईमेल पत्ता प्रविष्ट करा.',
      'auth_short_password': 'पासवर्ड किमान ६ अक्षरांचा असावा.',
      'auth_password_mismatch': 'पासवर्ड जुळत नाहीत.',
      'auth_account_exists': 'या ईमेलसह खाते आधीपासून अस्तित्वात आहे. कृपया लॉग इन करा.',
      'auth_email_registered_firebase': 'हा ईमेल आधीच नोंदणीकृत आहे. कृपया लॉग इन करा.',
      'auth_account_created_title': 'खाते यशस्वीरित्या तयार झाले!',
      'auth_account_created_sub': 'तुम्ही आता तुमच्या खात्यात लॉग इन करू शकता.',
      'auth_log_in_now': 'आत्ताच लॉग इन करा',
      'auth_incorrect_password': 'चुकीचा पासवर्ड. कृपया पुन्हा प्रयत्न करा.',
      'auth_account_not_found': 'खाते सापडले नाही. नवीन खाते तयार करण्यासाठी खाली "साइन अप करा" वर क्लिक करा.',
      'auth_failed': 'प्रमाणीकरण अयशस्वी',
      'auth_google_failed': 'गूगल साइन-इन अयशस्वी.',
      'auth_sign_out': 'साइन आउट करा',

      // Home Screen
      'home_greeting_morning': 'शुभ सकाळ,',
      'home_greeting_afternoon': 'शुभ दुपार,',
      'home_greeting_evening': 'शुभ संध्याकाळ,',
      'home_welcome_hero': 'वैयक्तिकृत AI त्वचा बुद्धिमत्ता',
      'home_start_scan_title': 'तुमच्या त्वचेचे विश्लेषण करा',
      'home_start_scan_sub': 'त्वरित AI विश्लेषण आणि GradCAM मॅपिंगसाठी फोटो घ्या किंवा अपलोड करा',
      'home_start_scan_button': 'त्वचा स्कॅन सुरू करा',
      'home_routine_title': 'आजची त्वचा काळजी दिनचर्या',
      'home_morning_routine': 'सकाळची दिनचर्या',
      'home_evening_routine': 'संध्याकाळची दिनचर्या',
      'home_custom_routine': 'कस्टम दिनचर्या',
      'home_no_routines': 'आजसाठी कोणतीही दिनचर्या नियोजित नाही.',
      'home_add_routine': 'दिनचर्या जोडा',
      'home_skin_score': 'त्वचा आरोग्य स्कोर',
      'home_recent_analysis': 'अलीकडील स्कॅन अहवाल',
      'home_view_all': 'सर्व पहा',
      'home_view_details': 'तपशील पहा',
      'home_myths_title': 'त्वचा काळजीचे समज आणि गैरसमज',
      'home_take_quiz': 'क्विझ घ्या',
      'home_quick_questionnaire': 'त्वचा प्रश्नावली पूर्ण करा',
      'home_quick_questionnaire_sub': 'सुलभ उत्पादने आणि दिनचर्या शिफारसी मिळवा',

      // Skin Scan Screen
      'scan_title': 'त्वचा स्कॅन आणि AI विश्लेषण',
      'scan_subtitle': 'स्थानिक मोबाइलनेटV2 अनुमान आणि सुरक्षित AI विश्लेषण',
      'scan_take_photo': 'फोटो घ्या',
      'scan_gallery': 'गॅलरीमधून निवडा',
      'scan_upload_prompt': 'तुमच्या त्वचेच्या भागाचा स्पष्ट फोटो घ्या किंवा अपलोड करा',
      'scan_analyzing': 'त्वचेचे विश्लेषण होत आहे...',
      'scan_processing_sub': 'मोबाइलनेटV2 न्युरल वैशिष्ट्य काढणे चालू आहे',
      'scan_condition_detected': 'आढळलेली स्थिती',
      'scan_confidence': 'अचूकता दर',
      'scan_secondary_possibilities': 'इतर शक्यता',
      'scan_region_analysis': 'चेहऱ्याच्या भागाचे विश्लेषण',
      'scan_gradcam_overlay': 'GradCAM व्हिज्युअल हीटमॅप',
      'scan_recommended_actions': 'शिफारस केलेल्या काळजी क्रिया',
      'scan_disclaimer': 'वैद्यकीय अस्वीकरण: स्किनकोर AI फक्त माहितीच्या मार्गदर्शनासाठी आहे. वैद्यकीय सल्ल्यासाठी त्वचाविकार तज्ज्ञांचा सल्ला घ्या.',
      'scan_retake': 'पुन्हा फोटो घ्या',
      'scan_save_report': 'अहवाल जतन करा',
      'scan_report_saved': 'अहवाल यशस्वीरित्या जतन केला!',

      // Questionnaire Screen
      'q_title': 'त्वचा प्रोफाइल प्रश्नावली',
      'q_subtitle': 'तुमच्या शिफारसी वैयक्तिकृत करण्यासाठी आम्हाला तुमच्या त्वचेबद्दल सांगा',
      'q_step': 'टप्पा',
      'q_of': 'पैकी',
      'q_skin_type': 'तुमच्या त्वचेचा मुख्य प्रकार कोणता आहे?',
      'q_primary_concern': 'तुमची मुख्य त्वचा समस्या कोणती आहे?',
      'q_sensitivity': 'तुमची त्वचा किती संवेदनशील आहे?',
      'q_sun_exposure': 'तुम्ही थेट उन्हात किती वेळा असता?',
      'q_budget': 'तुमची पसंतीची उत्पादन बजेट श्रेणी कोणती आहे?',
      'q_submit': 'प्रश्नावली सबमिट करा',
      'q_submitting': 'प्रोफाइल जतन करत आहे...',
      'q_success': 'प्रश्नावली यशस्वीरित्या पूर्ण झाली!',
      'q_retake': 'प्रश्नावली उत्तरे अपडेट करा',

      // Skin types & options
      'opt_oily': 'तेलकट (Oily)',
      'opt_dry': 'कोरडी (Dry)',
      'opt_combination': 'मिश्र (Combination)',
      'opt_normal': 'सामान्य (Normal)',
      'opt_sensitive': 'संवेदनशील (Sensitive)',
      'opt_acne': 'पिंपल्स आणि पुरळ (Acne)',
      'opt_aging': 'बारीक रेषा आणि सुरकुत्या',
      'opt_pigmentation': 'पिग्मेंटेशन आणि काळे डाग',
      'opt_redness': 'लाली (Redness)',
      'opt_low': 'कमी / सौम्य',
      'opt_medium': 'मध्यम',
      'opt_high': 'उच्च / संवेदनशील',
      'opt_budget_low': 'परवडणारे (₹ / \$)',
      'opt_budget_mid': 'मध्यम श्रेणी (₹₹ / \$\$)',
      'opt_budget_premium': 'प्रीमियम (₹₹₹ / \$\$\$)',

      // Products & Recommendations
      'reco_title': 'घटक-प्रथम शिफारसी',
      'reco_subtitle': 'तुमच्या त्वचेच्या विश्लेषणाशी जुळणारी उत्पादने',
      'reco_prereq_title': 'प्रथम तुमची प्रोफाइल पूर्ण करा',
      'reco_prereq_sub': 'वैयक्तिकृत उत्पादन शिफारसी अनलॉक करण्यासाठी त्वचा स्कॅन घ्या किंवा प्रश्नावली भरा.',
      'reco_prereq_scan_btn': 'त्वचा स्कॅन घ्या',
      'reco_prereq_q_btn': 'प्रश्नावली पूर्ण करा',
      'reco_tab_all': 'सर्व उत्पादने',
      'reco_tab_cleanser': 'क्लीन्झर',
      'reco_tab_moisturizer': 'मॉइश्चरायझर',
      'reco_tab_sunscreen': 'सनस्क्रीन',
      'reco_tab_serum': 'सीरम',
      'reco_tab_treatment': 'उपचार (Treatment)',
      'reco_suitable_high': 'अत्यंत योग्य',
      'reco_suitable_med': 'मध्यम योग्य',
      'reco_suitable_low': 'काळजीपूर्वक वापरा',
      'reco_why_recommended': 'शिफारस करण्याचे कारण',
      'reco_key_actives': 'मुख्य सक्रिय घटक',
      'reco_ingredients_avoid': 'टाळायचे घटक',
      'reco_usage_tips': 'वापर कसा करावा',
      'reco_buy_now': 'उत्पादन पहा / खरेदी करा',
      'reco_brand_neutral': 'ब्रांड तटस्थ आणि पारदर्शक',
      'reco_no_products': 'या श्रेणीसाठी कोणतीही उत्पादने सापडली नाहीत.',

      // Progress Tracker
      'tracker_title': 'प्रगती आणि इतिहास',
      'tracker_subtitle': 'तुमच्या त्वचा काळजी दिनचर्या आणि स्कॅन इतिहासाचा मागोवा घ्या',
      'tracker_routine_adherence': 'दिनचर्या पालन',
      'tracker_morning_done': 'सकाळची दिनचर्या पूर्ण झाली',
      'tracker_evening_done': 'संध्याकाळची दिनचर्या पूर्ण झाली',
      'tracker_streak': 'दिवसांची सातत्यता',
      'tracker_scan_history': 'स्कॅन इतिहास अहवाल',
      'tracker_no_history': 'अद्याप कोणताही स्कॅन अहवाल नोंदवला गेलेला नाही.',
      'tracker_add_routine_btn': '+ दिनचर्या आयटम जोडा',
      'tracker_routine_item_name': 'दिनचर्या आयटमचे नाव',
      'tracker_routine_time': 'वेळ',

      // Chatbot
      'chat_title': 'स्किनकोर AI सहाय्यक',
      'chat_subtitle': 'त्वचा काळजी, घटक किंवा दिनचर्या बद्दल विचार करा',
      'chat_placeholder': 'स्किनकोर AI ला तुमच्या त्वचेबद्दल विचारा...',
      'chat_disclaimer': 'AI सल्ला सामान्य जागरूकतेसाठी आहे. वैद्यकीय निदानासाठी डॉक्टरांचा सल्ला घ्या.',
      'chat_prompt_1': 'तेलकट त्वचेसाठी सर्वोत्तम दिनचर्या कोणती आहे?',
      'chat_prompt_2': 'सॅलिसिलिक ॲसिडचा सुरक्षित वापर कसा करावा?',
      'chat_prompt_3': 'सनस्क्रीन SPF रेटिंग स्पष्ट करा.',

      // Settings
      'settings_title': 'सेटिंग्ज आणि प्रोफाइल',
      'settings_dark_mode': 'डार्क मोड',
      'settings_smart_notifs': 'स्मार्ट सूचना',
      'settings_smart_notifs_sub': 'स्वयंचलित दिनचर्या स्मरणपत्रे',
      'settings_language': 'भाषा',
      'settings_privacy': 'गोपनीयता आणि डेटा',
      'settings_privacy_sub': 'डेटा, स्थानिक लॉग आणि कॅश व्यवस्थापित करा',
      'settings_clear_cache': 'स्कॅन कॅश साफ करा',
      'settings_export_data': 'डेटा निर्यात करा',
      'settings_delete_data': 'डेटा हटवा',
      'settings_delete_confirm_title': 'इतिहास हटवायचा?',
      'settings_delete_confirm_body': 'ही कृती पूर्ववत केली जाऊ शकत नाही. सर्व स्कॅन अहवाल हटवले जातील.',

      // Medical condition display labels
      'cond_acne_vulgaris': 'ॲक्ने / पिंपल्स (Acne Vulgaris)',
      'cond_eczema': 'एक्झिमा / खरुज (Eczema)',
      'cond_melasma': 'मेलास्मा / काळे डाग (Melasma)',
      'cond_rosacea': 'रोसेसिया / लाली (Rosacea)',
      'cond_psoriasis': 'सोरायसिस (Psoriasis)',
      'cond_normal_healthy': 'निरोगी त्वचा',
      'cond_unknown': 'त्वचा स्थिती विश्लेषण',
    },
  };

  String translate(String key) {
    final languageCode = locale.languageCode;
    final map = _localizedValues[languageCode];
    if (map != null && map.containsKey(key)) {
      return map[key]!;
    }
    // Safe Fallback to English
    return _localizedValues['en']?[key] ?? key;
  }

  // Handy getters for common strings
  String get appName => translate('app_name');
  String get languageSelect => translate('language_select');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'mr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
